name: CI

on:
  push:
    tags: [ '*' ]
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: coursier/cache-action@v6
      - uses: VirtusLab/scala-cli-setup@main

      - run: make test

  format:
    name: Check Formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: coursier/cache-action@v6
      - uses: VirtusLab/scala-cli-setup@main

      - run: make format-check

  check-and-upload-native-build-mac:
    name: Check Graal Build (Mac)
    runs-on: macos-latest
    needs: test

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: coursier/cache-action@v6
      - uses: VirtusLab/scala-cli-setup@main

      - run: make package

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: skan-x86_64-apple-darwin
          path: ./out/skan
          if-no-files-found: error
          retention-days: 5

  check-and-upload-native-build-linux:
    name: Check Graal Build (Linux)
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: coursier/cache-action@v6
      - uses: VirtusLab/scala-cli-setup@main

      - run: make package

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: skan-x86_64-linux
          path: ./out/skan
          if-no-files-found: error
          retention-days: 5

  check-and-upload-native-build-windows:
    name: Check Graal Build (Windows)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: coursier/cache-action@v6
      - uses: VirtusLab/scala-cli-setup@main

      - run: make package
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: skan-x86_64-win
          path: ./out/skan
          if-no-files-found: error
          retention-days: 5

  release:
    runs-on: ubuntu-latest
    needs: [ test, check-and-upload-native-build-linux, check-and-upload-native-build-mac]
    if: "startsWith(github.ref, 'refs/tags/')"
    steps:
      - uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Display structure of downloaded files
        run: ls -R

      - name: Prep releases
        run: bash .github/prepare-release.sh

      - name: Upload-to-release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: releases/*
          token: ${{ secrets.RELEASE_TOKEN }}
